### ISSUE TITLE
训练过程没有val的loss

### ISSUE THREAD

**Issue by YYL9404** [bubbliiiing/yolov4-pytorch#102]
![微信截图_20201028145433](https://user-images.githubusercontent.com/37946359/97402624-cd172180-192d-11eb-9c81-b730cd1f090f.png)
只有train的loss 没有val的，之前的步骤都是按照视频来的

**Comment by qinjiang007** [comment]
我的total loss 可以到30，但是val loss增大了，到90。怎么回事呢？发自我的华为手机-------- 原始邮件 --------发件人： YYL9404 <notifications@github.com>日期： 2020年10月28日周三 下午2:57收件人： bubbliiiing/yolov4-pytorch <yolov4-pytorch@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [bubbliiiing/yolov4-pytorch] 训练过程没有val的loss (#102)



只有train的loss 没有val的，之前的步骤都是按照视频来的

**Comment by bubbliiiing** [comment]
数据集过少吧

**Comment by YYL9404** [comment]
> 数据集过少吧

确定是这样的

**Comment by YYL9404** [comment]
> 我的total loss 可以到30，但是val loss增大了，到90。怎么回事呢？发自我的华为手机-------- 原始邮件 --------发件人： YYL9404 <notifications@github.com>日期： 2020年10月28日周三 下午2:57收件人： bubbliiiing/yolov4-pytorch <yolov4-pytorch@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主 题： [bubbliiiing/yolov4-pytorch] 训练过程没有val的loss (#102) 只有train的loss 没有val的，之前的步骤都是按照视频来的 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

那应该是过拟合了
