### ISSUE TITLE
冻结层训练完之后停止了，没有报错

### ISSUE THREAD

**Issue by Anleeno-Xu** [bubbliiiing/yolov4-pytorch#105]

**Comment by bubbliiiing** [comment]
啊哈？

**Comment by Anleeno-Xu** [comment]
这是什么原因呢，冻结层跑完后就停了，解冻后的训练不继续，还要手动把最后的权重接着训练










博
977821975@qq.com


---原始邮件---
发件人: "Bubbliiiing"<notifications@github.com&gt;
发送时间: 2020年11月6日(周五) 下午5:55
收件人: "bubbliiiing/yolov4-pytorch"<yolov4-pytorch@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Anleeno Xu"<977821975@qq.com&gt;;
主题: Re: [bubbliiiing/yolov4-pytorch] 冻结层训练完之后停止了，没有报错 (#105)




 
啊哈？
