### ISSUE TITLE
参数初始化方式

### ISSUE THREAD

**Issue by njustczr** [bubbliiiing/yolov4-pytorch#115]
我看backbone里面initial的方法，其实就是nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')吗？看了下nn.init.kaiming_normal_()的源码，打印了一下中间变量感觉是一样的。

**Comment by bubbliiiing** [comment]
emm，应该就是默认的初始化方法，我没有指定初始化（因为有coco的预训练权重，基本上之后head需要初始化了）
