### ISSUE TITLE
小改进，cpu与gpu加载模型

### ISSUE THREAD

**Issue by WZTENG** [bubbliiiing/yolov4-pytorch#12]
train.py与yolo.py中有使用torch.load()方法的建议加上map_location=xxx，防止gpu训练cpu预测或其它混用情况下报错。
比如可以改成这样：
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
pretrained_dict = torch.load(model_path, map_location=device)

**Comment by bubbliiiing** [comment]
已经加了CUDA参数了吧

**Comment by WZTENG** [comment]
> 已经加了CUDA参数了吧

跟cuda没关系，，是gpu保存，但使用cpu加载模型就会报错，要加上map_location，官方手册有说。

**Comment by bubbliiiing** [comment]
没搞懂，可以设置Cuda吧

**Comment by WZTENG** [comment]
> 没搞懂，可以设置Cuda吧

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.

If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

torch.load(opt.model,map_location=device)
类似这种错误，不一定会发生 ，大部分是gpu保存，但在只有cpu的机器上加载就会报错。

**Comment by bubbliiiing** [comment]
这个错误是在我这里发生的吗，我没有没有GPU的机子，没有试过

**Comment by WZTENG** [comment]
> 这个错误是在我这里发生的吗，我没有没有GPU的机子，没有试过

就是发生了，才看了下没有写才来说改进的，确实发生的。我是在云服务上训练，本地上跑的（没有GPU），发现没写map_location

**Comment by bubbliiiing** [comment]
行，那我修改一下

**Comment by bubbliiiing** [comment]
我先试试看
