### ISSUE TITLE
模型效果不好，想询问一下训练建议

### ISSUE THREAD

**Issue by lidc1004** [bubbliiiing/yolov4-pytorch#129]
我使用COCO数据的30个类别进行训练，使用数据增强，更改了自己数据的yolo_anchor，不解冻20个epoch，但效果不好，验证时很多类别都是0，不知道怎么继续训练，询问一下

**Comment by bubbliiiing** [comment]
我不了解你的具体训练过程，默认参数挺好的，你可能没修改好参数，anchor也是个问题

**Comment by lidc1004** [comment]
> 我不了解你的具体训练过程，默认参数挺好的，你可能没修改好参数，anchor也是个问题

后面可以了，谢谢大佬，我还想问一下就是混肴矩阵怎么计算，想生成混淆矩阵

**Comment by bubbliiiing** [comment]
混淆矩阵一般是用来计算miou的吧，目标检测一般不需要吧

**Comment by bubbliiiing** [comment]
不会用到一般感觉……

**Comment by lidc1004** [comment]
> 不会用到一般感觉……

我这需要用到，但是改的不对，不知道怎么改
