### ISSUE TITLE
同一个grid点,存在2个不同类别obj, 如何处理？

### ISSUE THREAD

**Issue by 184338740** [bubbliiiing/yolov4-pytorch#132]
作者你好，看过你的哔哩哔哩视频，并研读了下分享的代码，收益匪浅，非常感谢！
目前在运行kitti数据集时的000114.png图片时，出现在同一个分类feature map的同一个grid点，既有人，又有车，对应tcls为[1,0,1]
nets/yolo_training.py  
```
get_target():
    tcls[b, best_n, gj, gi, int(target[b][t, 4])] = 1
```
以上代码可能存在，同一个grid点，有两个不同类型物体的bug

**Comment by bubbliiiing** [comment]
你说的是不是训练的时候，这应该是yolov4本身设计就存在的问题，很多网络如centernet都有这个问题

**Comment by 184338740** [comment]
恩，是的。
另外，get_target()是在model 输入正方形图片上计算IOU， 再选出的anchor argmax index。像kitti这种，原图和resize之后存在严重长宽比形变的情况，可能存在从anchor A跳转到anchor B的情况。目前在考虑矩形推理方式，缓解该问题。

**Comment by bubbliiiing** [comment]
那就是一种改进了，可以写论文的

**Comment by jay121380** [comment]
那现在这个问题解决了没  使用推理方式

**Comment by bubbliiiing** [comment]
什么推理方式0 0
