### ISSUE TITLE
关于更改图片尺寸

### ISSUE THREAD

**Issue by QISIRUI** [bubbliiiing/yolov4-pytorch#136]
代码更改图片尺寸就会报错

RuntimeError:` invalid argument 0: Sizes of tensors must match except in dimension 1. Got 14 and 13 in dimension 2 at C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:71

During handling of the above exception, another exception occurred:
........
........
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not tuple

**Comment by bubbliiiing** [comment]
具体怎么更改的

**Comment by QISIRUI** [comment]
用的200x200的数据集，在train.py 和yolo.py里把input_shape和model_image_size改成了200x200

**Comment by vanchen523** [comment]
改成32的整数倍

**Comment by bubbliiiing** [comment]
是的

**Comment by QISIRUI** [comment]
好的，谢谢啦
