### ISSUE TITLE
精度比原论文低太多了吧

### ISSUE THREAD

**Issue by PoonKinWang** [bubbliiiing/yolov4-pytorch#141]
精度比原论文低太多了吧

**Comment by bubbliiiing** [comment]
加了letterbox_image后低的，直接resize反而高，但是我个人认为letterbox_image更合理。

**Comment by WilburZjh** [comment]
> 加了letterbox_image后低的，直接resize反而高，但是我个人认为letterbox_image更合理。

博主，请问这个letterbox_image是干嘛的啊？

**Comment by bubbliiiing** [comment]
给图像进行不失真的resize，给图片周围添加灰条，会使得图像主体不失真，但是也会使得图像主题比较小

**Comment by bubbliiiing** [comment]
关了letterbox_image了，精度重更新了一下
