### ISSUE TITLE
关于数据集分割

### ISSUE THREAD

**Issue by Anleeno-Xu** [bubbliiiing/yolov4-pytorch#160]
vocdevkit里面有一个数据集分割的代码，照理说这个和2007_xx.txt是对应的，但是多了一个trainval.txt
在train.py里面也有0.9:0.1的训练集和验证集分割，是从2007_train.txt里面分的。
这几个到底啥关系？感觉好像有冲突。希望耐心解答。

**Comment by bubbliiiing** [comment]
前者我的代码未进行分割，只用了train.txt
实际验证集分割在train.py里
