### ISSUE TITLE
自己训练后只能检测一个物体，不能同时检测多个

### ISSUE THREAD

**Issue by smallzhu** [bubbliiiing/yolov4-pytorch#165]
您好，我用yolov4 pytorch训练识别车牌，标签只有一类，但是训练后只能检测一个物体，不能检测多个，训练集采用的是CCPD，每张图片内也只有一个物体。请问您知道是什么原因吗

**Comment by bubbliiiing** [comment]
我不懂你的意思，检测效果是什么
