### ISSUE TITLE
想问一下为什么明明图片存在路径下，却说读取失败

### ISSUE THREAD

**Issue by Coderxiaobai1** [bubbliiiing/yolov4-pytorch#166]
![image](https://user-images.githubusercontent.com/43570323/110776644-45f29680-829b-11eb-8109-86cd707b05aa.png)

**Comment by Coderxiaobai1** [comment]
是因为我的图片中有下划线吗 wwwww

**Comment by bubbliiiing** [comment]
咦，下划线一般不影响，你确认有东西吗

**Comment by USTC-ChaoYu** [comment]
我也是同样的问题，等待大神解决
