### ISSUE TITLE
数据集的处理能不能使用k折交叉验证的方法

### ISSUE THREAD

**Issue by yangfei963158659** [bubbliiiing/yolov4-pytorch#18]
楼主，我看你数据集按9:1分为训练集和验证集来训练，但是每个epoch都是一样的。能不能在每个epoch里把数据按9:1分为训练集和验证集来训练，这就是说每个epoch的训练集和验证集在变化。也就是说数据集的处理能不能使用k折交叉验证的方法。

**Comment by bubbliiiing** [comment]
……目标检测不会使用K折交叉验证的，不是传统学习方法。
你想要验证，你修改一下np.random.seed，每一次都不一样

**Comment by yangfei963158659** [comment]
了解

**Comment by BalieyChan** [comment]
> 

请问您做出来了吗

**Comment by BalieyChan** [comment]
> ……目标检测不会使用K折交叉验证的，不是传统学习方法。 你想要验证，你修改一下np.random.seed，每一次都不一样

大神请问下，np.random.seed这个是啥呀，具体要咋修改呀？
