### ISSUE TITLE
TypeError: cat() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by Ray-Y0ung** [bubbliiiing/yolov4-pytorch#2]
遇到的一个bug
完整错误提示
Traceback (most recent call last):
  File "C:/Users/zhq/Desktop/maskdect/yolov4-pytorch-master/train.py", line 178, in <module>
    fit_ont_epoch(net,yolo_losses,epoch,epoch_size,epoch_size_val,gen,gen_val,Freeze_Epoch,Cuda)
  File "C:/Users/zhq/Desktop/maskdect/yolov4-pytorch-master/train.py", line 49, in fit_ont_epoch
    outputs = net(images)
  File "D:\Program_Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program_Files\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\Program_Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\zhq\Desktop\maskdect\yolov4-pytorch-master\nets\yolo4.py", line 129, in forward
    P4 = torch.cat([P4,P5_upsample],axis=1)
TypeError: cat() got an unexpected keyword argument 'axis'

我查了一下，发现相关给出的建议都是针对tf的，还没有好的解决办法

**Comment by bubbliiiing** [comment]
torch版本不同吧，是不是版本错了，1.2.0

**Comment by CallHoganZhang** [comment]
> 遇到的一个bug
> 完整错误提示
> Traceback (most recent call last):
> File "C:/Users/zhq/Desktop/maskdect/yolov4-pytorch-master/train.py", line 178, in
> fit_ont_epoch(net,yolo_losses,epoch,epoch_size,epoch_size_val,gen,gen_val,Freeze_Epoch,Cuda)
> File "C:/Users/zhq/Desktop/maskdect/yolov4-pytorch-master/train.py", line 49, in fit_ont_epoch
> outputs = net(images)
> File "D:\Program_Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "D:\Program_Files\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
> return self.module(*inputs[0], **kwargs[0])
> File "D:\Program_Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\zhq\Desktop\maskdect\yolov4-pytorch-master\nets\yolo4.py", line 129, in forward
> P4 = torch.cat([P4,P5_upsample],axis=1)
> TypeError: cat() got an unexpected keyword argument 'axis'
> 
> 我查了一下，发现相关给出的建议都是针对tf的，还没有好的解决办法

您好，我也遇到这个问题，请问这个问题解决了吗？已经解决的话可以分享思路吗

**Comment by bubbliiiing** [comment]
版本

**Comment by JackMT** [comment]
我用torch1.2.0会出现，用torch1.4.0没有出现

**Comment by bubbliiiing** [comment]
这样吗。。。。。我是用1.2.0
