### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by dtjun** [bubbliiiing/yolov4-pytorch#212]
我在训练的时候观察到随着epoch的增加，total loss是在不断减小的，但每一个iter的损失的波动越来越大。
以下是我个人的理解：
    1. 这个现象说明有一部分拟合的越来越好，有一部分拟合的越来越差。
    2. 在训练的代码中，是先把dataset和dataloader定义好了，然后再进行循环，所以在每一个epoch中的，接受的数据的顺序都是一样的，这样就人为的导致了数据不均衡（个人理解）
    3. 所以我把gen的定义copy到for循环中了，每一个循环都通过shuffle对数据的顺序进行打乱。
跟着up主学的，不知道这样有没有道理，坐等回复。ψ(｀∇´)ψ

**Comment by bubbliiiing** [comment]
1、前面是不断的下降，后面基本拟合了所以才波动的。
2、每一个epoch都会遍历全部的数据，数据集内部类别不平衡的话没什么办法
3、自带打乱

**Comment by dtjun** [comment]
嗯嗯，理解了，dataloader在每个epoch循环的时候都会再从内存中读取数据，所以顺序还会被打乱。
