### ISSUE TITLE
class YOLO(object) 初始化函数感觉少了条语句

### ISSUE THREAD

**Issue by dsp6414** [bubbliiiing/yolov4-pytorch#23]
def __init__(self, **kwargs):
        self.__dict__.update(self._defaults)
        self.__dict__.update(**kwargs)  #感觉要加上这句，不然初始化参数就没意义了

yolo = YOLO(model_path='model_data/best.pth',cuda=False)

**Comment by dsp6414** [comment]
代码部分显示感觉有问题__都没显示出来

**Comment by dsp6414** [comment]
而且代码仅用self.cuda判断是有bug的，
比如self.cuda为True, 但机器如果没有gpu或torch是cpu版本的，执行过程就会有bug

**Comment by bubbliiiing** [comment]
1、代码的哪个地方
2、什么显示不出来
3、self.cuda只是为了判断是否用cuda，自由度更高，我在训练东西的时候我都可以把Cuda设置成False，这个时候我就能预测或者训练试试看代码是否正确。如果机器没有GPU却不知道设置CUDA的话，我觉得可能基础还要加强一下。

**Comment by dsp6414** [comment]
根目录yolo.py里Yolo类的代码。

**Comment by bubbliiiing** [comment]
class YOLO(object):
    _defaults = {
        "model_path": 'model_data/yolo4_weights.pth',
        "anchors_path": 'model_data/yolo_anchors.txt',
        "classes_path": 'model_data/coco_classes.txt',
        "model_image_size" : (416, 416, 3),
        "confidence": 0.5,
        "cuda": True
    }

    @classmethod
    def get_defaults(cls, n):
        if n in cls._defaults:
            return cls._defaults[n]
        else:
            return "Unrecognized attribute name '" + n + "'"

    #---------------------------------------------------#
    #   初始化YOLO
    #---------------------------------------------------#
    def __init__(self, **kwargs):
        self.__dict__.update(self._defaults)
        self.class_names = self._get_class()
        self.anchors = self._get_anchors()
        self.generate()

**Comment by bubbliiiing** [comment]
不是有吗

**Comment by dsp6414** [comment]
我明白你的意思，都在default里设置参数，像我第一问那样传参创建就没法用了

**Comment by dsp6414** [comment]
只是建议哈

**Comment by bubbliiiing** [comment]
没听太懂…不是在init的时候已经update过了吗

**Comment by dsp6414** [comment]
我意思是你固定死了参数，创建时传参怎么办，每次来yolo.py文件里改吗？算没没说哈😄

**Comment by WZTENG** [comment]
加上这个：self.__dict__.update(**kwargs)
然后在实例的时候可以直接传参数就不用改代码了
 yolo = YOLO(**{'model_path': 'model_data/yolo4_weights.pth',
                   'classes_path': 'model_data/coco_classes.txt'})

**Comment by WZTENG** [comment]
> 加上这个：self.**dict**.update(**kwargs) 然后在实例的时候可以直接传参数就不用改代码了 yolo = YOLO(**{'model_path': 'model_data/yolo4_weights.pth',
> 'classes_path': 'model_data/coco_classes.txt'})

哎，，怎么字典前面的2个星号不显示。。
