### ISSUE TITLE
训练过程计算loss为什么不用整个batch计算而需要循环

### ISSUE THREAD

**Issue by XinkaiJi** [bubbliiiing/yolov4-pytorch#246]
训练过程计算loss为什么不用整个batch计算而需要循环
            for l in range(len(outputs)):
                loss_item, num_pos = yolo_loss(l, outputs[l], targets)
                loss_value_all  += loss_item
                num_pos_all     += num_pos
            loss_value = loss_value_all / num_pos_all

**Comment by bubbliiiing** [comment]
0 0暂时米有，之后有计划加进去
