### ISSUE TITLE
训练过程中loss值震荡问题

### ISSUE THREAD

**Issue by XuecWu** [bubbliiiing/yolov4-pytorch#249]
泡泡哥您好，最近我在COCO-2014/2017以及您提供的VOC数据集上进行训练，我的bs是16，lr是0.0001，结果发现loss值随epoch的变化十分的震荡，之后我使用未经过修改的YOLOv4并且按照您提供的原始参数进行训练，结果依旧十分的震荡。所以想来听听您的看法。谢谢！下图是loss的曲线
![image](https://user-images.githubusercontent.com/75833531/148642239-6b098fff-90cd-4f45-9154-7bbc0e90ffbc.png)

**Comment by XuecWu** [comment]
此时我还正在训练，完全是按照您提供的原始超参数来的并使用了您提供的voc的预训练权重，我想听听哥您的看法，或许是咱模型本身的问题还是说因为我的哪里没有设置好。谢谢！

**Comment by XuecWu** [comment]
上面的loss曲线，我所使用的是未改动的YOLOv4，使用原先设定好的超参数，使用哥您提供的VOC数据集以及您提供的预训练权重文件。

**Comment by XuecWu** [comment]
还有一点就是，咱的代码使用Dropblock了嘛哥，相关代码段我没有找到==

**Comment by ChinaRush** [comment]
试一试把batchsize调大

**Comment by XuecWu** [comment]
> 试一试把batchsize调大
我测试过啦，当我从头开始训练时，loss-epoch曲线显得不那么震荡，并且通过观察可以发现，最上面的这张图里面的loss值变化虽然呈现出震荡形式，但其值还是在呈现出一个下降趋势，谢谢啦

**Comment by bubbliiiing** [comment]
因为开了个cosine，我得把cosine重置一下，感觉pytorch自带的cosine不对

**Comment by XuecWu** [comment]
好类哥，我说咋看着这个变化跟余弦函数这么像哈哈哈

**Comment by XuecWu** [comment]
> 因为开了个cosine，我得把cosine重置一下，感觉pytorch自带的cosine不对
还有一个问题就是在我在向COCO测评服务器提交测评结果时，一直报下面这个错误，意思就是我上交的结果不符合它服务器的格式，可是我生成的json文件（下图2）是使用COCOAPI的方法生成的，但是它所提供的结果的实例（下图3）是这种形式的，所以我想问问真的是json格式存在问题还是说因为其他呢
![7f863ad9548c0865e62fabcd9277511](https://user-images.githubusercontent.com/75833531/149272996-9bb0d4e3-563f-4f8e-8239-f51edbdead78.png)
![7bd15ae62c248fbb840f9a83cd7ffe8](https://user-images.githubusercontent.com/75833531/149273005-e74b6589-ed69-4382-8bb7-01375d68ffd0.png)
![a97329a5dd9948ea56bc82d53b56630](https://user-images.githubusercontent.com/75833531/149273016-802de89f-08cf-4f91-a0a0-a0a43b4e8374.png)

**Comment by bubbliiiing** [comment]
emmm，你可以试试用我那个mode=4试试0 0

**Comment by XuecWu** [comment]
> emmm，你可以试试用我那个mode=4试试0 0

哥我一直用的就是get_map的mode=4呀，我把那里给改了一下，改成只生成预测结果的，最终生成的结果就是上面的图2那种形式的呀，但上交到服务器就会报上面的那个错误555555

**Comment by bubbliiiing** [comment]
https://blog.csdn.net/weixin_38705903/article/details/104887008
这个断言的作用是：判断你的json文件内，所有image的id是否和你annotations中出现的图片id有对应

后来发现，我有一些图片里面是空，这张图片上没有annotations，所以id的数量会对不上，只需要把没有注释的图片从json文件中删除就好了~
可能是你有些图没检测到东西

**Comment by XuecWu** [comment]
嗯嗯，我再试试，谢谢哥，还有就是最近在训练COCO的时候发现，有时候刚开始的loss值特别大，这是什么原因呢哥

**Comment by bubbliiiing** [comment]
这个yolo是这样，最近在看yolo5，准备改一下损失

**Comment by XuecWu** [comment]
最近两次训练起初的loss值都很高，在830左右，哥我这样训练完之后所得的数据会正常嘛？我记得您之前说过，loss值的大小并不能准确反映变化的情况，我们应关注变化的趋势，但是这个loss值看着挺害怕的哈哈哈。

**Comment by bubbliiiing** [comment]
正常
