### ISSUE TITLE
训练过程中存在的一些问题

### ISSUE THREAD

**Issue by XuecWu** [bubbliiiing/yolov4-pytorch#265]
@bubbliiiing 哥这部分为啥要再写一遍呢，前面不是已经写过了嘛
![7211adf334ef3a36db40441e3590669](https://user-images.githubusercontent.com/75833531/156289880-f99cdcab-d600-4254-bf11-b83a90c705b9.png)
还有前几个星期我就已经在使用这套训练代码了，我现在COCO2017的训练集上跑，使用的是带有warmup的cosine（您参考YOLOX的那套），设定的是300个epoch，其中冰冻了40个，冰冻时的bs是64，不冰冻是32，我对自适应学习率调整那里动了一下，然后这样我从训练一开始我的学习率就是0.001，我使用的是Adam，现在训到220轮了，学习率是0.000143，但是结果还是很不好，目前COCO的map只有0.20左右 
学习率下降的很慢，一次下降0.000004左右，目前220轮仍是0.000143，loss的下降也很慢，一次最多能降0.02（情况很少）我在想效果不好的原因是因为学习率还没下降到一定的程度？还是说因为其他的
我现在相当于是在做消融实验，并没有采用mosaic，网络结构我目前只对head进行了修改。

**Comment by XuecWu** [comment]
@bubbliiiing  哥我感觉按照这个样子，300轮训完的效果也不会太好啊害，那个学习率的下降公式我算了一下，也没啥问题啊这
用之前的训练方案，冻住backbone，训100个epoch都能有0.36的mAP，现在220轮了才0.2害

**Comment by XuecWu** [comment]
冻住backbone只训练neck和head，loss值下降的还可以，冰冻阶段最后一个epoch的效果能到0.27，但一开始全部训练，loss下降的就慢了。并且如果单纯的只冻住bakcbone进行训练，效果到一定轮数之后就不会提升了

**Comment by XuecWu** [comment]
哥您可以加下我的vx嘛哥，有些事情真的想和您讨论讨论，这个工作我已经做了两个月了，真的对我特别特别重要，我的vx是wxc161188，真麻烦您了哥

**Comment by bubbliiiing** [comment]
不要用Adam，用SGD会好一些。

**Comment by bubbliiiing** [comment]
然后学习率设置1e-2。会好很多，Adam的weight_decay有问题

**Comment by bubbliiiing** [comment]
这个训练方案我在yolo3上训练过，200代可以复现yolo3的精度，v4我实在没算力复现

**Comment by XuecWu** [comment]
@bubbliiiing 好的哥，那我就按照您设定的参数来做，您这样说我就有底气了，我使用SGD+YOLOX的cosine-warmup试一下

**Comment by bubbliiiing** [comment]
嗯……你重下一下库，然后只改Unfreeze epoch

**Comment by bubbliiiing** [comment]
和batchsize，其它的别变，我不知道你改了多少，至少train.py是这样

**Comment by XuecWu** [comment]
我想的是我直接不冰冻训练了吧哥，直接整300个，但是这样我的batch_size只能有32，那按照初始设定的学习率0.01，再加上根据batch_size自适应调整的学习率，那初始的学习率就直接变成0.005了哥

**Comment by bubbliiiing** [comment]
初始5e-4，三个epoch后5e-3

**Comment by XuecWu** [comment]
我还有必要将学习率重新改成0.01嘛，就是在这种batch_size=32的情况下

**Comment by bubbliiiing** [comment]
哎大哥，你先试试吧。或者你先试试v3。然后用主干的预训练

**Comment by bubbliiiing** [comment]
你用了吗

**Comment by XuecWu** [comment]
主干的预训练我肯定用了呀哥，就只加载这个主干的权重来训的

**Comment by bubbliiiing** [comment]
我训练的参数就是
freeze batch 64
unfreeze batch 32
pretrain = True
Init lr = 1e-2
UnFreeze Epoch = 200
cos学习率

**Comment by XuecWu** [comment]
ok哥知道了，老弟还有一个问题，就是哥这个主干的预训练权重是您从darknet官方那里拿过来了叭？

**Comment by bubbliiiing** [comment]
均为转换的

**Comment by XuecWu** [comment]
好的知道了谢谢哥麻烦您了

**Comment by XuecWu** [comment]
@bubbliiiing 哥一共300代这都130多代了，mAP咋还这么低害
![5ae49c8a7fde62f411133a5f5503bd9](https://user-images.githubusercontent.com/75833531/157782129-2572f7e6-af15-4154-893b-538f98af5a88.png)

**Comment by XuecWu** [comment]
最近权重的loss的值的变化
![image](https://user-images.githubusercontent.com/75833531/157782759-11d2537b-92db-4060-8dca-d100c506c810.png)

**Comment by bubbliiiing** [comment]
这个是他们那个库吗？可能和数据集有关系吧

**Comment by XuecWu** [comment]
@bubbliiiing  我现在用的是您最新更新的库，然后按照您说的默认参数，我修改的只是epoch的总数，我设为了300，在COCO2017train上训练，现在150代左右了效果还只有23左右的mAP

**Comment by XuecWu** [comment]
@bubbliiiing 哥你能给我看一下那时候您在COCO2017训练YOLOv3的loss曲线嘛想参考下，我这个loss还是下降的很慢

**Comment by XuecWu** [comment]
我能确信的是我的标签和数据集都没有问题并且我还去除了脏数据

**Comment by bubbliiiing** [comment]
150代的学习率还才降了一半不到吧？

**Comment by bubbliiiing** [comment]
23挺正常的

**Comment by XuecWu** [comment]
@bubbliiiing  哥现在学习率是0.002左右，刚解冻的时候学习率是0.0045

**Comment by bubbliiiing** [comment]
没吧……先训练吧…

**Comment by XuecWu** [comment]
行哥我知道了，还是学习率太高了，等它学习率下降了再看看效果，谢谢哥了

**Comment by XuecWu** [comment]
还有就是哥您训练的时候开mosaic了嘛开了的话您感觉它稳定不稳定呀哥，我记得您之前说过mosaic有点儿不稳定来着

**Comment by summer261** [comment]
@XuecWu 我想问一下，训练结果的权重文件上的AP是怎么搞得啊

**Comment by summer261** [comment]
@XuecWu 哥，我想问一下，训练结果的权重文件上的AP是怎么搞得啊

**Comment by XuecWu** [comment]
@summer261 自己测得，加载训练好的权重来进行测试

**Comment by summer261** [comment]
@XuecWu 可以一次把所有得测出来？

**Comment by XuecWu** [comment]
测试你划分好的测试集

**Comment by bubbliiiing** [comment]
> 测试你划分好的测试集

训练的怎么样？效果如何？

**Comment by XuecWu** [comment]
还没跑完了哥，现在225代 COCOval2017上33.4的AP

**Comment by XuecWu** [comment]
@bubbliiiing 学习率现在是0.0005左右
![image](https://user-images.githubusercontent.com/75833531/158306168-d42e91f7-2ac8-4609-bf07-301c8b0871bd.png)

**Comment by XuecWu** [comment]
哥我现在对这个mosaic有点儿疑惑，我不太清楚它的使用效果，但看YOLOX论文里面说的它作用挺大的哈哈

**Comment by bubbliiiing** [comment]
呀？怎么loss还有个上升的过程

**Comment by bubbliiiing** [comment]
你上次没有这个过程呀

**Comment by bubbliiiing** [comment]
我看成我自己的图了0 0……

**Comment by XuecWu** [comment]
这个我也可奇怪，它不是解冻之后上升的，它是到70代左右上升的，然后又慢慢降下去了，哥上面那个是你发的呀

**Comment by XuecWu** [comment]
> 我看成我自己的图了0 0……

哈哈哈

**Comment by bubbliiiing** [comment]
0 0是啊，为什么呢，正常不会有这个上升，难道跑飞了？

**Comment by XuecWu** [comment]
从这儿就开始了，大约到第110代就又开始下降了
![image](https://user-images.githubusercontent.com/75833531/158307896-c576f352-2f92-4284-ba89-97e2f44d51a8.png)

**Comment by bubbliiiing** [comment]
太奇怪了……理论上应该一直在下降，这个时候学习率时没有上升的……我感觉时跑飞了的0 0

**Comment by bubbliiiing** [comment]
你的batch是多少呀

**Comment by bubbliiiing** [comment]
是32吗？

**Comment by XuecWu** [comment]
> 是32吗？

对的解冻的batch是32，冰冻的是64

**Comment by XuecWu** [comment]
难道还是因为解冻然后权重全部训练让它的loss变大了？不应该吧

**Comment by bubbliiiing** [comment]
我感觉有点迷茫0 0，不知道最后能到多少，但是感觉到不了40多

**Comment by bubbliiiing** [comment]
不应该，你是70上升的，要是解冻上升的话，应该是50上升

**Comment by bubbliiiing** [comment]
0 0你这个现在还没我yolo3精度高，惊呆

**Comment by bubbliiiing** [comment]
你用的是我提供的utils_coco吗

**Comment by XuecWu** [comment]
是的，是用那个文件来计算的，我也感觉可离谱，我没有使用mosaic

**Comment by bubbliiiing** [comment]
噢……没有mosaic倒也正常

**Comment by bubbliiiing** [comment]
mosaic影响还蛮大的

**Comment by XuecWu** [comment]
对因为想把mosaic放到接下来的消融实验里面所以这次就没用，但这个loss的上升跟mosaic有很大的关系嘛哥

**Comment by bubbliiiing** [comment]
loss上升我确实不知道为什么……不应该的

**Comment by bubbliiiing** [comment]
感觉就是跑飞了0 0………………

**Comment by bubbliiiing** [comment]
我觉得上升影响还蛮大的，白优化了这么久

**Comment by bubbliiiing** [comment]
但是却不知道是为什么0 0。。

**Comment by XuecWu** [comment]
是啊害

**Comment by XuecWu** [comment]
不过现在loss下降的还算差不多把

**Comment by bubbliiiing** [comment]
看看训练的差不多怎么样吧…感觉应该是到35-38的样子…虽然不合理但也合理，不过这种网络训练太慢了…寻常人家根本玩不起…

**Comment by XuecWu** [comment]
是阿，一训训两个星期，一直占着服务器可不好意思了

**Comment by XuecWu** [comment]
刚才又测了下，229代34.3的AP

**Comment by XuecWu** [comment]
在50代之后其实整个验证集的loss都是比较震荡的

**Comment by bubbliiiing** [comment]
其实应该是直接从非冻结开始，不应该有冻结过程的

**Comment by bubbliiiing** [comment]
忘了提醒了，我是直接unfreeze的

**Comment by bubbliiiing** [comment]
我的代码没有针对服务器优化，所以速度慢一点点，每次要加载很多图片，如果服务器内存足够的情况下，应该可以一次性载入所有图片，调用就好了

**Comment by XuecWu** [comment]
> 其实应该是直接从非冻结开始，不应该有冻结过程的

没有这个冻结过程可能更符合端到端的训练把

**Comment by bubbliiiing** [comment]
有个cos的过程，提前让backbone接受训练会稳定一些

**Comment by XuecWu** [comment]
嗯嗯，下次就直接unfreeze开始了，那这样初始学习率就是0.005，batch_size就是32了，还有就是哥你感觉训多少代合适呢

**Comment by XuecWu** [comment]
我咋感觉200代也是可以的呀，现在看来，只要学习率下降到位了，效果就会提升，是这样的嘛

**Comment by bubbliiiing** [comment]
有点差距，但差距没有很大，可能半个点到一个点
多搜索一下总是好事

**Comment by XuecWu** [comment]
嗯嗯好的哥我知道了，等结果出来了跟你说一声儿

**Comment by XuecWu** [comment]
我标签平滑的值设置的是0.005，这个没啥大影响把哥

**Comment by bubbliiiing** [comment]
貌似这玩意没啥用，反正我没用它

**Comment by XuecWu** [comment]
哈哈哈

**Comment by XuecWu** [comment]
@bubbliiiing 感觉这个loss的上升，最合理的解释还是因为解冻导致的把，它在第51代有个小幅度的loss上升，之后又下降回去了。要不是这里的原因，那它理应不应该突然上升的把QAQ
图1训练集loss 图2验证集loss
![99e6daa550d4055cc0bb2a35953f714](https://user-images.githubusercontent.com/75833531/158392625-b5f8d492-ee55-44eb-8277-9d294dc58bb0.png)
![image](https://user-images.githubusercontent.com/75833531/158392703-a3bf9793-50de-47ce-9192-aaaf3c202418.png)

**Comment by bubbliiiing** [comment]
这个图是60才上升的不是51耶

**Comment by bubbliiiing** [comment]
所以我才觉得非常不合理呀0 0，真的不应该60的

**Comment by bubbliiiing** [comment]
确实是看不懂0 0

**Comment by XuecWu** [comment]
太奇怪了也0 0，马上跑完了就这样把hhh

**Comment by XuecWu** [comment]
@bubbliiiing 哥我使用奇数张卡，比如说3张，会对BN这些操作或者说对模型的性能造成影响嘛

**Comment by bubbliiiing** [comment]
没有影响应该，不过好像大多数是偶数，不过应该没事

**Comment by XuecWu** [comment]
okok知道了老哥

**Comment by XuecWu** [comment]
@bubbliiiing 哥我有一个问题就是，我们进行断点续练，这个会对模型最终的性能表现造成影响嘛？这一点我一直不太清楚

**Comment by XuecWu** [comment]
哥还有一个问题就是，比如说我第101代的时候训练终止了，那么我应该加载第100代的权重，那这个时候我的Init_epoch的值就应该设定为100嘛哥

**Comment by bubbliiiing** [comment]
1、影响不大 
2、嗯对，权值上的数字是多少，就写多少。
你最后效果如何呢

**Comment by XuecWu** [comment]
> 1、影响不大 2、嗯对，权值上的数字是多少，就写多少。 你最后效果如何呢

基线那组已经做完啦哥608*608的输入42的AP把，不是特别理想，没有开mosaic，现在我为了加速，换成416*416的了

**Comment by bubbliiiing** [comment]
42的好像已经蛮高的了啊，你看yolov4论文，就是43

**Comment by XuecWu** [comment]
哥这是在COCOval2017上测得，我没在test-dev上测

**Comment by bubbliiiing** [comment]
test不是一般比val高吗

**Comment by XuecWu** [comment]
啊这个我不知道呀，我用那个官方的权重测COCOval2017能到48左右的AP

**Comment by bubbliiiing** [comment]
因为darknet连val一起训练了吧好像

**Comment by XuecWu** [comment]
哦哦这样啊哥，我知道了，可能还是因为上升的那段的原因把，然后我训300代，到那个270代左右的时候验证集的loss基本上不改变了就

**Comment by bubbliiiing** [comment]
差距已经很小了可以说，人家batch好像还比你大呢

**Comment by bubbliiiing** [comment]
最后收敛的那段居然提升那么大么，我记得你说前面才30多

**Comment by XuecWu** [comment]
从200轮到300轮相当是涨了10个AP点

**Comment by bubbliiiing** [comment]
可以~看来实践出真知，我自己之前都不知道，我还一直以为我的代码不是那么靠谱

**Comment by bubbliiiing** [comment]
😄

**Comment by XuecWu** [comment]
哥昨天加的那个Focal loss效果咋样你测试了嘛

**Comment by bubbliiiing** [comment]
没卡，没测……最近在搞毕业的事，只是加上去了，跑的通而已

**Comment by XuecWu** [comment]
现在我在训的是自己改进的网络，batch是64，不冰冻直接训的，总共260代，现在125代左右，AP是20左右，学习率是0.00492，哥这是不是还是因为学习率没降下来呀

**Comment by bubbliiiing** [comment]
只是最高峰的1/2，正常，再训训。

**Comment by XuecWu** [comment]
> 没卡，没测……最近在搞毕业的事，只是加上去了，跑的通而已

行我这几组跑完了我测测，估计会久一点。啊这哥，我以为你都毕业了呢，这是硕士毕业还是博士毕业啊哥

**Comment by XuecWu** [comment]
> 只是最高峰的1/2，正常，再训训。

ok知道了哥

**Comment by XuecWu** [comment]
@bubbliiiing 哥你提供的那个COCO的预训练权重是从v4官方拿的哪一版的呀，是608*608输入大小还是哪一种呢

**Comment by XuecWu** [comment]
还有就是我从darknet官方那里下载了它的权重文件，它是weights格式的，这个改咋转换成pth格式的呀哥

**Comment by bubbliiiing** [comment]
忘了，应该608的吧

**Comment by bubbliiiing** [comment]
我这里没代码了，删了已经
