### ISSUE TITLE
loss的大致范围

### ISSUE THREAD

**Issue by Willianwatch** [bubbliiiing/yolov4-pytorch#268]
你好，我在做三维目标检测，我觉得您这个repo的yolov4代码比较清晰，就把它改成三维的版本了，但是我的loss都到两万多了，感觉有点不正常，请问下你在训练的时候loss大致是多少呀？

**Comment by bubbliiiing** [comment]
新的代码应该是最多20，最低0.05差不多，记不清

**Comment by Willianwatch** [comment]
好的，谢谢！

**Comment by bubbliiiing** [comment]
加油
