### ISSUE TITLE
Train from scratch

### ISSUE THREAD

**Issue by huansu** [bubbliiiing/yolov4-pytorch#279]
博主，我把VOC2007从零开始训练，没有使用预训练权重，相当于Train from scratch，得到的mAP只有58.x，这正常吗？没有改动你其他地方的代码。

**Comment by XuecWu** [comment]
@huansu Hi，VOC2007相对而言还是比较小的，最起码要加载下bavkbone的权重，如果想train from scratch，可以去COCO上尝试尝试

**Comment by bubbliiiing** [comment]
yes，你试试yolov5 Train from scratch 07+12，效果可以到80差不多，1是yolov5模型比较小，2是07+12数据集大点

**Comment by XuecWu** [comment]
> yes，你试试yolov5 Train from scratch 07+12，效果可以到80差不多，1是yolov5模型比较小，2是07+12数据集大点

对于yolov4 yolov5这种，我从头开始训效果应该不会太好的把哥

**Comment by bubbliiiing** [comment]
v5都是从头的，yolox也是，直接300代，前255代只用mosaic，还是270代，忘了

**Comment by XuecWu** [comment]
> v5都是从头的，yolox也是，直接300代，前255代只用mosaic，还是270代，忘了

270代，mosaic设的是0.7
