### ISSUE TITLE
cuda问题请教

### ISSUE THREAD

**Issue by zcdliuwei** [bubbliiiing/yolov4-pytorch#28]
请问大佬，您使用的GPU驱动是什么版本，我的是NVIDIA 10.1，在使用您的代码时报错，驱动太老，请问这个问题怎么解决，必须要升级驱动吗

**Comment by bubbliiiing** [comment]
你有看过我的bilibili视频吗，具体的你需要把你的显卡，cuda，cudnn都发给我

**Comment by zcdliuwei** [comment]
我没有看您的视频教程，这个问题我已经解决了，谢谢您的回复。

另外，我惊喜发现了您的另一个仓库：https://github.com/bubbliiiing/yolov4-tf2，
我在学习TF2，我想研究一下您的代码，请问，您上面那个仓库，是实现了yolov4论文中的全部模块吗 ？

**Comment by zcdliuwei** [comment]
您上面的仓库，仓库名写的是yolov4-tf2，描述写的是yolo3-tf2

**Comment by bubbliiiing** [comment]
yolov4，基本上实现了，但是没有能力全部实现
