### ISSUE TITLE
map计算的可视化的问题

### ISSUE THREAD

**Issue by 3097254259** [bubbliiiing/yolov4-pytorch#293]
第一次设置 map_vis  = False，运行成功了，然后设置map_vis = True，也运行成功了，但是再次设置map_vis  = False时仍然运行的是可视化效果，试了很多次没有解决，有大佬知道原因吗？

**Comment by bubbliiiing** [comment]
map_vis……可视化的东西可能和你想想的不一样吧

**Comment by 3097254259** [comment]
可能我没有表达清楚，就是我设置了false，但是那个可视化的animation框仍在。
![8$Y JC47 I3R7 ~C7)UMBQP](https://user-images.githubusercontent.com/74974285/163319623-53be8466-8d9a-4cc7-9dc6-d3a828101309.png)
![ID5$ZSX@XVG%SGIG4IJ)XP](https://user-images.githubusercontent.com/74974285/163319720-52a903a3-6922-436c-a01c-2de74be92096.jpg)

**Comment by 3097254259** [comment]
感谢，已经解决了，我把map_out下的文件全部删除了 就可以了

**Comment by bubbliiiing** [comment]
实我唐突了……有点菜
