### ISSUE TITLE
关于Backnone的预训练权重

### ISSUE THREAD

**Issue by LittlelittleZ** [bubbliiiing/yolov4-pytorch#297]
您好，我想请问现在有基于ImageNet 1k的预训练骨干网络权重吗，我现在打算做个比赛，要求只能够使用ImageNet 1k的预训练权重，第一次接触目标检测，不太熟悉，如有打扰请见谅！

**Comment by bubbliiiing** [comment]
你看网盘…

**Comment by LittlelittleZ** [comment]
> 你看网盘…

我看了的，那个backbone权重就是用ImageNet 1k训的吗，我看您的readme里没有说明这个backbone的预训练数据集，所以想确认一下。GitHub有一些其他人复现的用的是其他数据集之类的，加上我对目标检测的套路目前不是很了解，所以可能问了个蠢问题，不好意思。

**Comment by bubbliiiing** [comment]
![image](https://user-images.githubusercontent.com/47347516/164584448-396d81f9-9e7c-4168-bd01-f7f43a0168c6.png)

**Comment by bubbliiiing** [comment]
backbone imagenet的

**Comment by LittlelittleZ** [comment]
> backbone imagenet的

明白，真的谢谢您！！！
