### ISSUE TITLE
kmeans_for_anchors问题

### ISSUE THREAD

**Issue by 3097254259** [bubbliiiing/yolov4-pytorch#298]
大佬，kmeans_for_anchors.py怎么用啊，是直接点运行就可以了吗，我看那个训练的的时候好像没用到这个py文件呀？

**Comment by bubbliiiing** [comment]
有需要的人用

**Comment by 3097254259** [comment]
我的数据集的打的标签的标记框基本都是很细长的框框，我可以用kmeans重新聚类吗，用那个py文件发自我的荣耀手机-------- 原始邮件 --------发件人： Bubbliiiing ***@***.***>日期： 2022年4月20日周三 22:31收件人： bubbliiiing/yolov4-pytorch ***@***.***>抄送： HongliEmperor ***@***.***>, Author ***@***.***>主    题： Re: [bubbliiiing/yolov4-pytorch] kmeans_for_anchors问题 (Issue #298)

额外的一些工具而已

**Comment by 3097254259** [comment]
我的数据集的打的标签的标记框基本都是很细长的框框，我可以用kmeans重新聚类吗，用那个py文件

**Comment by 3097254259** [comment]
我的训练对象 和 检测对象只有一类，先验眶需要kmeans聚类吗

**Comment by 3097254259** [comment]
![image](https://user-images.githubusercontent.com/74974285/164424522-5fee17a9-f3da-404d-82e0-63c0312c10fc.png)
我的聚类结果是这样的是不是就可以往yolo_anchors.txt里面写入 93，12， 141，20，145，39，217，29等等了

**Comment by bubbliiiing** [comment]
我生成了txt，直接复制进去，但是你这个框分布不好

**Comment by bubbliiiing** [comment]
建议理解一下先验框的作用，自己手动设置

**Comment by 3097254259** [comment]
> 

大佬，你说对了，我之前用原始anchors，map=74%，我换成我数据集重新聚类的anchors，map只有33%了，但是我看很多论文里都有根据自己的数据集重新kmeans聚类啊，效果都挺好的，这是怎么一回事呢？
![image](https://user-images.githubusercontent.com/74974285/164652215-48d67c6a-c1b8-4929-8f97-c3eecfe110f7.png)

**Comment by bubbliiiing** [comment]
1、……很多论文有水份
2、聚类出来的大中小分布要统一，可能他们自己调整了，说实话一般的效果都不好
