### ISSUE TITLE
显卡占用不均的问题。

### ISSUE THREAD

**Issue by deemoo-wang** [bubbliiiing/yolov4-pytorch#319]

**Comment by deemoo-wang** [comment]
想请教一下，多卡分布式运行的时候，第一张显卡的内存占用比其他的大，其他显卡的进程号也会使用第一张显卡的内存，这个是什么原因呢，能不占用第一张显卡吗

**Comment by bubbliiiing** [comment]
为啥捏，我这里就差了一千多，可能是因为我只是双卡，另外的进程是干嘛的呢

**Comment by bubbliiiing** [comment]
试出来了，utils/utils_fit里面的cuda()没有加上local rank

**Comment by deemoo-wang** [comment]
嗯，问题解决了，多谢啦！！

**Comment by zweiwei98** [comment]
作者你好，请教一下，`local rank`这个参数是有什么作用的？有点迷糊 @bubbliiiing

**Comment by bubbliiiing** [comment]
分布式使用

**Comment by zengww1998** [comment]
> 分布式使用

谢谢解答！
