### ISSUE TITLE
请问unit/dataloder.py 的第60行计算框的中心是不是漏了个括号，

### ISSUE THREAD

**Issue by 201661242ljw** [bubbliiiing/yolov4-pytorch#325]
unit/dataloder.py 的第60行是：
 box[:, 0:2] = box[:, 0:2] + box[:, 2:4] / 2

是否应该改为
 box[:, 0:2] = （box[:, 0:2] + box[:, 2:4]） / 2

原来代码确实能跑通，效果也不错，但今天看这里感觉这个计算框的中心从原理上讲好像不太对
或者说是不是我理解错了

**Comment by bubbliiiing** [comment]
你理解错了，0:2前面修改过了

**Comment by 201661242ljw** [comment]
明白了，确实，一时没反应过来

> 你理解错了，0:2前面修改过了
