### ISSUE TITLE
请问加载yolov5_s.pt权重时为什么会报下面这个问题

### ISSUE THREAD

**Issue by NuaaYH** [bubbliiiing/yolov4-pytorch#346]
Fail To Load Key: ['yolo_head_P3.weight', 'yolo_head_P3.bias', 'yolo_head_P4.weight', 'yolo_head_P4.bias', 'yolo_head_P5.weight', 'yolo_head_P5.bias'] ……

**Comment by yaoweini** [comment]
I also met this problem. How u handled this?
