### ISSUE TITLE
dataloader的目的是什么呢

### ISSUE THREAD

**Issue by Fafa-DL** [bubbliiiing/yolov4-pytorch#35]
你好，在改进的train中我看到了dataloader的使用，请问其目的是什么呢？

**Comment by WZTENG** [comment]
> 你好，在改进的train中我看到了dataloader的使用，请问其目的是什么呢？

这是pytorch自带的数据加载方式，有多线程可以加速训练速度。

**Comment by bubbliiiing** [comment]
是
