### ISSUE TITLE
请问，训练时只修改过类别数，如何才能获取到对应的cfg文件？

### ISSUE THREAD

**Issue by tosonw** [bubbliiiing/yolov4-pytorch#5]
训练出的模型转为onnx时需要用到cfg文件，可这里没有对应的cfg文件，我使用官网的cfg修改了classes和batch等参数后，任然会报错：TypeError: buffer is too small for requested array  ，我查询资料说是cfg文件不对应，请问如何获取到对应的cfg文件呢？？

**Comment by bubbliiiing** [comment]
emm我没有学过caffe，对cfg文件不了解

**Comment by tosonw** [comment]
@bubbliiiing 好的，麻烦你了

**Comment by terrynx** [comment]
> 训练出的模型转为onnx时需要用到cfg文件，可这里没有对应的cfg文件，我使用官网的cfg修改了classes和batch等参数后，任然会报错：TypeError: buffer is too small for requested array ，我查询资料说是cfg文件不对应，请问如何获取到对应的cfg文件呢？？

你好，请问你转onnx成功了么
