### ISSUE TITLE
小物体数据集训练后模型地loss很快收敛,但测试图片的检测效果不好？

### ISSUE THREAD

**Issue by LY54** [bubbliiiing/yolov4-pytorch#52]
您好，我用检测目标是小物体地数据集训练后，模型地loss很快收敛并且训练验证损失值收敛在0.037。但测试图片的检测效果不好，图片含有目标但没有检测到，且整张图上没有看到检测框。
于是我试了下训练集中的图片，依旧检测不出来目标。我做的训练集图片大小是608X608，是按照您的ReadMe中的步骤修改了anchors，和class，进行训练和测试的

**Comment by bubbliiiing** [comment]
检查2007_train.txt，应该没有目标信息吧。

**Comment by LY54** [comment]
是的，看了一下，我生成的2007_train.txt中只包含了图片位置，没有图片其真实框的位置。

**Comment by LY54** [comment]
感谢您的指导

**Comment by LY54** [comment]
我想在请问您一下，为什么我用您的代码生成的2007_train.txt中只包含了图片位置，没有图片其真实框的位置，我该怎么解决这个问题

**Comment by LY54** [comment]
解决了，谢谢
