### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by WZTENG** [bubbliiiing/yolov4-pytorch#6]
感谢大佬的代码！
在自己改造数据集加载为pytorch的Dataset类时，用plt显示__getitem__()方法获取的图片时，发现mosaic为true获取的图片显示为黑色，经过调试发现:
get_random_data()方法的图片会经过>>除255再乘255
get_random_data_with_Mosaic()方法会经过>>除255再乘255又除255
最终mosaic显示为黑色，只要去掉mosaic方法内的最后一个除255就可以了。
请问这个是预期的嘛？

**Comment by dsp6414** [comment]
voc_annotation.py产生的训练集
不是直接读xml数据么，代码里生成的数据就是（x0，y0，x1，y1）格式呀。

**Comment by WZTENG** [comment]
> voc_annotation.py产生的训练集
> 不是直接读xml数据么，代码里生成的数据就是（x0，y0，x1，y1）格式呀。

是经过处理后返回的数据，不是直接读取xml里面的，，处理后变成了中心点加宽高的百分比了，也不是坐标。已经弄明白了。

**Comment by dsp6414** [comment]
感觉我们不在一个频道。我说的是up主生成的那个2007_train.txt,里面的坐标就是绝对坐标呀。

**Comment by WZTENG** [comment]
> 感觉我们不在一个频道。我说的是up主生成的那个2007_train.txt,里面的坐标就是绝对坐标呀。

已经解决了。是传入网络的数据是中心点加宽高，而且是百分比，不是txt文件里面的。

**Comment by bubbliiiing** [comment]
Emm是有这个问题，我忘了改掉了，不过分布是一样的所以也可以训练
