### ISSUE TITLE
pth权重下载点

### ISSUE THREAD

**Issue by Chad-Lu** [bubbliiiing/yolov4-pytorch#60]
你好，我想下在预训练权重，但是显示网页不存在，可以提供新的连结吗?

**Comment by bubbliiiing** [comment]
我可以打开，你换个浏览器试试，百度网盘

**Comment by 108368062** [comment]
你好，可以重新開啟連結的權限嗎?目前進不去了，感謝

**Comment by bubbliiiing** [comment]
你再试试，我可以进

**Comment by 108368062** [comment]
請問連結是這樣對吧?請問哪種瀏覽器開得起來，我的都說頁面不存在，聽說有擋台灣IP是嗎?
https://pan.baidu.com/s/1VNSYi39AaqjHVbdNpW_7sw

**Comment by 108368062** [comment]
我後來進得去了，感謝，順便借串幫忙同樣進不去的，可以試試VPN，可以正常打開連結。
