### ISSUE TITLE
数据集方面的问题

### ISSUE THREAD

**Issue by WZTENG** [bubbliiiing/yolov4-pytorch#7]
通过打印框的位置感觉有问题，请问大佬是不是验证过图像增强的过程？
![image](https://user-images.githubusercontent.com/19603468/83247584-4ae7cd00-a1d6-11ea-8e26-0af733ee370d.png)
![image](https://user-images.githubusercontent.com/19603468/83247602-50451780-a1d6-11ea-98ec-f84d57724920.png)

**Comment by dsp6414** [comment]
我测试了下yymnist数据集，检测结果没问题。

**Comment by WZTENG** [comment]
> 它训练数据集是绝对坐标形式，（x0，y0，x1，y1）格式，而不是(xc,yc,w,h)格式。

已经知道了，数据格式是中心点加宽高，不是左上角跟右下角
