### ISSUE TITLE
关于cspdarknet53的权重

### ISSUE THREAD

**Issue by njustczr** [bubbliiiing/yolov4-pytorch#80]
训练在voc或者coco数据集上训练yolov4的时候，初始化backbone的cspdarknet53在imagenet数据集上的权重是自己训练的吗？

**Comment by bubbliiiing** [comment]
整个yolov4都是ab大神那转化的…

**Comment by njustczr** [comment]
> 整个yolov4都是ab大神那转化的…

ok，明白了，多谢
