### ISSUE TITLE
cspdarknet53的结构问题

### ISSUE THREAD

**Issue by njustczr** [bubbliiiing/yolov4-pytorch#91]
cspdarknet53的cfg，我参考的https://github.com/AlexeyAB/darknet官方的cfg，以第一个stage为例，参差边后面接的shortcut，我用netron可视化网络结构，看到shortcut的属性如下截图：
![image](https://user-images.githubusercontent.com/30426320/95651458-1f2e0980-0b1d-11eb-8a77-ac8cf957226d.png)
activation显示的是linear，但是我看你cspdarknet结构里面写的还是conv+bn+mish不知道是不是有问题？我参考cfg搭的网络这个shortcut改成1X1的conv的话，imagenet上分类指标top1 acc一直差2%，不知道是不是这个问题？

**Comment by bubbliiiing** [comment]
你的图我看不见，shortcut不是只有在有shape变化的时候才使用卷积么，其它时候是直接短接，shape变化短接边没有卷积要怎么改变shape

**Comment by njustczr** [comment]
> 你的图我看不见，shortcut不是只有在有shape变化的时候才使用卷积么，其它时候是直接短接，shape变化短接边没有卷积要怎么改变shape

多谢！哈哈，是我结构搞错了，按照你的结构修改指标正常了
