### ISSUE TITLE
关于pretrained model

### ISSUE THREAD

**Issue by morn2333** [bubbliiiing/yolov4-pytorch#93]
请问下您公开的两个模型 yolo4_voc_weights.pth 和yolo4_weights.pth 是以什么作为pretrain训练得到的呀，还是从0开始训练出来的？如果我想用yolov4原作者开放的在imagenet上训练的darknet backbone 预训练模型 yolov4.conv.137， 有办法可以把它转换成您的网络可以加载的格式吗？

**Comment by morn2333** [comment]
我找到转换的方法啦

**Comment by bubbliiiing** [comment]
芜湖，可以分享一下吗，我学习一下

**Comment by morn2333** [comment]
这个代码 https://github.com/Tianxiaomo/pytorch-YOLOv4 可以加载源代码的cfg文件和yolov4.conv.137 并且inference，所以我就用他的代码加载了模型又保存成了 .pth格式，然后把key和你的CSPDarknet的结构一一匹配，对应加载了
![修改](https://user-images.githubusercontent.com/46912041/96220616-9ea75700-0fbb-11eb-88a0-6b96a905e419.png)

**Comment by bubbliiiing** [comment]
好的！
